# Copyright 2020 Changkun Ou. All rights reserved.
# Use of this source code is governed by a MIT
# license that can be found in the LICENSE file.

version: "3"
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main
    restart: always
    image: main:latest
    ports:
      - "9121:9121"